language: python
python:
   - "2.7"
   - "3.3"
   - "3.4"
   - "3.5"
   - "3.6"
install:
  - pip install coveralls
  - make install
script:
  - make test
  - make lint
after_success:
  - coveralls
notifications:
  email: false
